In [1]:
from sklearn.svm import SVC
from sklearn import svm
import numpy as np

x=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y=np.array([-1,-1,-1,1,1,1])

clf=SVC(C=1e5,kernel='linear')
clf.fit(x,y)

print('w= ',clf.coef_)
print('b= ',clf.intercept_)
print('Indices of support vectors = ',clf.support_)
print('Support vectors = ',clf.support_vectors_)
print('Number of support vectors for each class =',clf.n_support_)
print('Coefficients of the support vector in the decison function = ',np.abs(clf.dual_coef_))

w=  [[ 0.25 -0.25]]
b=  [-0.75]
Indices of support vectors =  [2 3]
Support vectors =  [[ 2.  3.]
 [ 6. -1.]]
Number of support vectors for each class = [1 1]
Coefficients of the support vector in the decison function =  [[0.0625 0.0625]]


In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plot
df=pd.read_csv('F:\Download\glass.csv')
df.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [3]:
x=df.drop('Type',axis=1)
y=df.Type

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [5]:

linear=svm.SVC(kernel='linear')
linear.fit(x_train,y_train)

SVC(kernel='linear')

In [37]:
print(linear.support_vectors_)

[[7.00000e+01 1.52300e+00 1.33100e+01 3.58000e+00 8.20000e-01 7.19900e+01
  1.20000e-01 1.01700e+01 0.00000e+00 3.00000e-02]
 [1.44000e+02 1.51709e+00 1.30000e+01 3.47000e+00 1.79000e+00 7.27200e+01
  6.60000e-01 8.18000e+00 0.00000e+00 0.00000e+00]
 [7.20000e+01 1.51848e+00 1.36400e+01 3.87000e+00 1.27000e+00 7.19600e+01
  5.40000e-01 8.32000e+00 0.00000e+00 3.20000e-01]
 [1.47000e+02 1.51769e+00 1.36500e+01 3.66000e+00 1.11000e+00 7.27700e+01
  1.10000e-01 8.60000e+00 0.00000e+00 0.00000e+00]
 [1.63000e+02 1.52211e+00 1.41900e+01 3.78000e+00 9.10000e-01 7.13600e+01
  2.30000e-01 9.14000e+00 0.00000e+00 3.70000e-01]
 [1.69000e+02 1.51666e+00 1.28600e+01 0.00000e+00 1.83000e+00 7.38800e+01
  9.70000e-01 1.01700e+01 0.00000e+00 0.00000e+00]
 [1.64000e+02 1.51514e+00 1.40100e+01 2.68000e+00 3.50000e+00 6.98900e+01
  1.68000e+00 5.87000e+00 2.20000e+00 0.00000e+00]
 [1.75000e+02 1.52058e+00 1.28500e+01 1.61000e+00 2.17000e+00 7.21800e+01
  7.60000e-01 9.70000e+00 2.40000e-01 5.10000e-01]


In [6]:
print(linear.n_support_)

[1 2 2 3 3 4]


In [7]:
y_pred=linear.predict(x_test)

In [8]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))

1.0


In [9]:
print(confusion_matrix(y_test,y_pred))

[[26  0  0  0  0  0]
 [ 0 12  0  0  0  0]
 [ 0  0  4  0  0  0]
 [ 0  0  0  6  0  0]
 [ 0  0  0  0  4  0]
 [ 0  0  0  0  0 13]]


In [10]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        26
           2       1.00      1.00      1.00        12
           3       1.00      1.00      1.00         4
           5       1.00      1.00      1.00         6
           6       1.00      1.00      1.00         4
           7       1.00      1.00      1.00        13

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65



In [11]:
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')

In [12]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [13]:
ypred1=model1.predict(x_test)
ypred2=model2.predict(x_test)
ypred3=model3.predict(x_test)

In [14]:
print(accuracy_score(y_test,ypred1))

0.47692307692307695


In [15]:
print(accuracy_score(y_test,ypred2))

0.9692307692307692


In [16]:
print(accuracy_score(y_test,ypred3))

0.7384615384615385
